// <auto-generated />
using System;
using CadastroCompleto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadastroCompleto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801182902_AddTelefonesEMocks")]
    partial class AddTelefonesEMocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadastroCompleto.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrgaoExpedidor")
                        .HasColumnType("integer");

                    b.Property<string>("RgOuCin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Cpf = "123.456.789-01",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1990, 3, 15),
                            Email = "joao.almeida@email.com",
                            EstadoCivil = 0,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "João Pedro Almeida",
                            OrgaoExpedidor = 24,
                            RgOuCin = "12.345.678-9"
                        },
                        new
                        {
                            ClienteId = 2,
                            Cpf = "234.567.890-12",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1985, 7, 22),
                            Email = "maria.costa@email.com",
                            EstadoCivil = 1,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Maria Fernanda Costa",
                            OrgaoExpedidor = 18,
                            RgOuCin = "23.456.789-0"
                        },
                        new
                        {
                            ClienteId = 3,
                            Cpf = "345.678.901-23",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1978, 11, 3),
                            Email = "carlos.souza@email.com",
                            EstadoCivil = 2,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Carlos Eduardo Souza",
                            OrgaoExpedidor = 12,
                            RgOuCin = "34.567.890-1"
                        },
                        new
                        {
                            ClienteId = 4,
                            Cpf = "456.789.012-34",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 13, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1995, 1, 30),
                            Email = "ana.lima@email.com",
                            EstadoCivil = 0,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Ana Beatriz Lima",
                            OrgaoExpedidor = 20,
                            RgOuCin = "45.678.901-2"
                        },
                        new
                        {
                            ClienteId = 5,
                            Cpf = "567.890.123-45",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 14, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1988, 9, 17),
                            Email = "pedro.rocha@email.com",
                            EstadoCivil = 1,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Pedro Henrique Rocha",
                            OrgaoExpedidor = 15,
                            RgOuCin = "56.789.012-3"
                        },
                        new
                        {
                            ClienteId = 6,
                            Cpf = "678.901.234-56",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1992, 4, 8),
                            Email = "juliana.alves@email.com",
                            EstadoCivil = 0,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Juliana Martins Alves",
                            OrgaoExpedidor = 23,
                            RgOuCin = "67.890.123-4"
                        },
                        new
                        {
                            ClienteId = 7,
                            Cpf = "789.012.345-67",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1980, 6, 25),
                            Email = "rafael.dias@email.com",
                            EstadoCivil = 3,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Rafael Nascimento Dias",
                            OrgaoExpedidor = 4,
                            RgOuCin = "78.901.234-5"
                        },
                        new
                        {
                            ClienteId = 8,
                            Cpf = "890.123.456-78",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1997, 12, 5),
                            Email = "fernanda.santos@email.com",
                            EstadoCivil = 0,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Fernanda Oliveira Santos",
                            OrgaoExpedidor = 8,
                            RgOuCin = "89.012.345-6"
                        },
                        new
                        {
                            ClienteId = 9,
                            Cpf = "901.234.567-89",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1983, 2, 14),
                            Email = "lucas.ferreira@email.com",
                            EstadoCivil = 1,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Lucas Gabriel Ferreira",
                            OrgaoExpedidor = 6,
                            RgOuCin = "90.123.456-7"
                        },
                        new
                        {
                            ClienteId = 10,
                            Cpf = "012.345.678-90",
                            DataCriacao = new DateTimeOffset(new DateTime(2024, 1, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataNascimento = new DateOnly(1991, 10, 19),
                            Email = "camila.torres@email.com",
                            EstadoCivil = 2,
                            Nacionalidade = "Brasileira",
                            NomeCompleto = "Camila Ribeiro Torres",
                            OrgaoExpedidor = 5,
                            RgOuCin = "01.234.567-8"
                        });
                });

            modelBuilder.Entity("CadastroCompleto.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnderecoId"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("EnderecoId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            EnderecoId = 1,
                            Bairro = "Centro",
                            Cep = "01000-000",
                            Cidade = "São Paulo",
                            ClienteId = 1,
                            Complemento = "Apto 32",
                            Estado = 24,
                            Numero = 120,
                            Rua = "Rua das Flores"
                        },
                        new
                        {
                            EnderecoId = 2,
                            Bairro = "Copacabana",
                            Cep = "22010-000",
                            Cidade = "Rio de Janeiro",
                            ClienteId = 2,
                            Estado = 18,
                            Numero = 850,
                            Rua = "Av. Atlântica"
                        },
                        new
                        {
                            EnderecoId = 3,
                            Bairro = "Savassi",
                            Cep = "30130-150",
                            Cidade = "Belo Horizonte",
                            ClienteId = 3,
                            Complemento = "Casa",
                            Estado = 12,
                            Numero = 45,
                            Rua = "Rua Pernambuco"
                        },
                        new
                        {
                            EnderecoId = 4,
                            Bairro = "Moinhos de Vento",
                            Cep = "90570-080",
                            Cidade = "Porto Alegre",
                            ClienteId = 4,
                            Complemento = "Bloco B",
                            Estado = 20,
                            Numero = 210,
                            Rua = "Rua Padre Chagas"
                        },
                        new
                        {
                            EnderecoId = 5,
                            Bairro = "Batel",
                            Cep = "80420-090",
                            Cidade = "Curitiba",
                            ClienteId = 5,
                            Complemento = "Sala 12",
                            Estado = 15,
                            Numero = 1500,
                            Rua = "Av. do Batel"
                        },
                        new
                        {
                            EnderecoId = 6,
                            Bairro = "Centro",
                            Cep = "88010-000",
                            Cidade = "Florianópolis",
                            ClienteId = 6,
                            Estado = 23,
                            Numero = 320,
                            Rua = "Rua Felipe Schmidt"
                        },
                        new
                        {
                            EnderecoId = 7,
                            Bairro = "Barra",
                            Cep = "40140-130",
                            Cidade = "Salvador",
                            ClienteId = 7,
                            Complemento = "Apto 501",
                            Estado = 4,
                            Numero = 780,
                            Rua = "Av. Oceânica"
                        },
                        new
                        {
                            EnderecoId = 8,
                            Bairro = "Setor Bueno",
                            Cep = "74223-060",
                            Cidade = "Goiânia",
                            ClienteId = 8,
                            Complemento = "Casa 2",
                            Estado = 8,
                            Numero = 655,
                            Rua = "Rua T-30"
                        },
                        new
                        {
                            EnderecoId = 9,
                            Bairro = "Asa Sul",
                            Cep = "70347-000",
                            Cidade = "Brasília",
                            ClienteId = 9,
                            Complemento = "Bloco C",
                            Estado = 6,
                            Numero = 12,
                            Rua = "SQS 108"
                        },
                        new
                        {
                            EnderecoId = 10,
                            Bairro = "Meireles",
                            Cep = "60165-121",
                            Cidade = "Fortaleza",
                            ClienteId = 10,
                            Complemento = "Apto 1201",
                            Estado = 5,
                            Numero = 990,
                            Rua = "Av. Beira Mar"
                        });
                });

            modelBuilder.Entity("CadastroCompleto.Models.Telefone", b =>
                {
                    b.Property<int>("TelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelefoneId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("TelefoneId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Telefone");

                    b.HasData(
                        new
                        {
                            TelefoneId = 1,
                            ClienteId = 1,
                            Ddd = "11",
                            Numero = "987654321",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 2,
                            ClienteId = 1,
                            Ddd = "11",
                            Numero = "33221100",
                            Tipo = 2
                        },
                        new
                        {
                            TelefoneId = 3,
                            ClienteId = 1,
                            Ddd = "11",
                            Numero = "32109876",
                            Tipo = 1
                        },
                        new
                        {
                            TelefoneId = 4,
                            ClienteId = 2,
                            Ddd = "21",
                            Numero = "976543210",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 5,
                            ClienteId = 3,
                            Ddd = "31",
                            Numero = "965432109",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 6,
                            ClienteId = 3,
                            Ddd = "31",
                            Numero = "32211009",
                            Tipo = 1
                        },
                        new
                        {
                            TelefoneId = 7,
                            ClienteId = 4,
                            Ddd = "51",
                            Numero = "954321098",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 8,
                            ClienteId = 5,
                            Ddd = "41",
                            Numero = "943210987",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 9,
                            ClienteId = 5,
                            Ddd = "41",
                            Numero = "31100998",
                            Tipo = 2
                        },
                        new
                        {
                            TelefoneId = 10,
                            ClienteId = 5,
                            Ddd = "41",
                            Numero = "30099887",
                            Tipo = 1
                        },
                        new
                        {
                            TelefoneId = 11,
                            ClienteId = 6,
                            Ddd = "48",
                            Numero = "932109876",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 12,
                            ClienteId = 6,
                            Ddd = "48",
                            Numero = "30988776",
                            Tipo = 2
                        },
                        new
                        {
                            TelefoneId = 13,
                            ClienteId = 7,
                            Ddd = "71",
                            Numero = "921098765",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 14,
                            ClienteId = 8,
                            Ddd = "62",
                            Numero = "910987654",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 15,
                            ClienteId = 8,
                            Ddd = "62",
                            Numero = "30877665",
                            Tipo = 2
                        },
                        new
                        {
                            TelefoneId = 16,
                            ClienteId = 8,
                            Ddd = "62",
                            Numero = "32166554",
                            Tipo = 1
                        },
                        new
                        {
                            TelefoneId = 17,
                            ClienteId = 9,
                            Ddd = "61",
                            Numero = "909876543",
                            Tipo = 0
                        },
                        new
                        {
                            TelefoneId = 18,
                            ClienteId = 9,
                            Ddd = "61",
                            Numero = "32055443",
                            Tipo = 1
                        },
                        new
                        {
                            TelefoneId = 19,
                            ClienteId = 10,
                            Ddd = "85",
                            Numero = "898765432",
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("CadastroCompleto.Models.Endereco", b =>
                {
                    b.HasOne("CadastroCompleto.Models.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("CadastroCompleto.Models.Endereco", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CadastroCompleto.Models.Telefone", b =>
                {
                    b.HasOne("CadastroCompleto.Models.Cliente", "Cliente")
                        .WithMany("Telefones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CadastroCompleto.Models.Cliente", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
